#!/usr/bin/env python3
"""Validate current/generated/archive/phase artifact lifecycle boundaries."""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

_SCRIPT_ROOT = next((p for p in Path(__file__).resolve().parents if (p / "lib").is_dir()), None)
if _SCRIPT_ROOT is not None and str(_SCRIPT_ROOT) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_ROOT))

from lib.mfos_lint import Finding, ROOT, emit, load_yaml, mode_arg


PHASE_NAME_RE = re.compile(r"(?:pre[-_]?phase[-_]?\d+|phase[-_]\d+(?:[-_]\d+)*)", re.IGNORECASE)
REPORT_CURRENT = ROOT / "reports/current"
REPORT_GENERATED = ROOT / "reports/generated"
REPORT_PHASES = ROOT / "reports/phases"
REPORT_ARCHIVE = ROOT / "reports/archive"
REPORT_INDEX = ROOT / "reports/index.yml"


def yaml_top(path: Path) -> dict[str, Any]:
    if path.suffix not in {".yml", ".yaml"}:
        return {}
    data = load_yaml(path)
    return data if isinstance(data, dict) else {}


def generated_marker(data: dict[str, Any]) -> bool:
    generated_by = data.get("generated_by") or data.get("generator")
    return data.get("status") == "generated" or (
        isinstance(generated_by, str) and generated_by.startswith("scripts/")
    )


def markdown_generated_marker(path: Path) -> bool:
    if path.suffix != ".md":
        return False
    head = "\n".join(path.read_text(encoding="utf-8").splitlines()[:20]).lower()
    return "generated by `scripts/" in head or "generated_by: scripts/" in head or "generator: scripts/" in head


def generated_report_names() -> set[str]:
    if not REPORT_INDEX.exists():
        return set()
    data = load_yaml(REPORT_INDEX)
    if not isinstance(data, dict):
        return set()
    names: set[str] = set()
    for item in data.get("generated_reports", []) if isinstance(data.get("generated_reports"), list) else []:
        if isinstance(item, dict) and isinstance(item.get("path"), str):
            names.add(Path(item["path"]).name)
    return names


def phase_path_component(path: Path) -> bool:
    try:
        rel = path.relative_to(REPORT_CURRENT)
    except ValueError:
        return False
    return any(PHASE_NAME_RE.fullmatch(part) for part in rel.parts)


def report_files(root: Path) -> list[Path]:
    if not root.exists():
        return []
    return sorted(path for path in root.rglob("*") if path.is_file())


def main() -> int:
    parser = mode_arg()
    args = parser.parse_args()
    findings: list[Finding] = []
    generated_names = generated_report_names()

    for path in report_files(REPORT_CURRENT):
        rel = path.relative_to(ROOT)
        if path.name in {"README.md", "index.yml", ".mfos-dir.yml"}:
            continue
        if PHASE_NAME_RE.search(path.name) or phase_path_component(path):
            findings.append(Finding("ERROR", path, "phase-specific report path is forbidden under reports/current"))
        data = yaml_top(path)
        if generated_marker(data) or markdown_generated_marker(path):
            findings.append(Finding("ERROR", path, "script-generated report artifact is forbidden under reports/current"))
        if path.suffix == ".md" and path.name in generated_names:
            findings.append(Finding("ERROR", path, "generated Markdown report belongs under reports/generated, not reports/current"))

    for root, label in ((REPORT_GENERATED, "generated"), (REPORT_PHASES, "phase"), (REPORT_ARCHIVE, "archive")):
        if not root.exists():
            findings.append(Finding("ERROR", root, f"{label} report lifecycle root is missing"))

    for path in report_files(REPORT_GENERATED):
        rel = path.relative_to(REPORT_GENERATED)
        if path.name in {"README.md", "index.yml", ".mfos-dir.yml"}:
            continue
        if not (rel.parts and (rel.parts[0].startswith("phase-") or len(rel.parts) == 1)):
            findings.append(Finding("ERROR", path, "generated report must be under reports/generated/phase-* or indexed top-level generated output"))

    for path in sorted(REPORT_PHASES.iterdir() if REPORT_PHASES.exists() else []):
        if path.is_dir() and not path.name.startswith("phase-") and path.name not in {"README.md"}:
            findings.append(Finding("ERROR", path, "phase report directory must use reports/phases/phase-*"))

    return emit(findings, args.mode, "Artifact lifecycle boundary check OK")


if __name__ == "__main__":
    raise SystemExit(main())
